const products = [
    {
      _id: '1',
      name: 'Classic White T-Shirt',
      image: '/images/white-tshirt.jpg',
      description: 'A timeless classic white t-shirt made from 100% cotton.',
      brand: 'FashionCo',
      category: 'T-Shirts',
      price: 19.99,
      countInStock: 15,
      rating: 4.5,
      numReviews: 10,
    },
    {
      _id: '2',
      name: 'Denim Jeans',
      image: '/images/denim-jeans.jpg',
      description: 'High-quality denim jeans with a comfortable fit.',
      brand: 'DenimWorld',
      category: 'Jeans',
      price: 49.99,
      countInStock: 20,
      rating: 4.7,
      numReviews: 25,
    },
    {
      _id: '3',
      name: 'Leather Jacket',
      image: '/images/leather-jacket.jpg',
      description: 'Stylish leather jacket with a modern design.',
      brand: 'UrbanStyle',
      category: 'Jackets',
      price: 129.99,
      countInStock: 5,
      rating: 4.9,
      numReviews: 15,
    },
    {
      _id: '4',
      name: 'Black Dress',
      image: '/images/black-dress.jpg',
      description: 'Elegant black dress perfect for any occasion.',
      brand: 'Glamour',
      category: 'Dresses',
      price: 79.99,
      countInStock: 8,
      rating: 4.8,
      numReviews: 12,
    },
    {
      _id: '5',
      name: 'Casual Hoodie',
      image: '/images/casual-hoodie.jpg',
      description: 'Comfortable hoodie for everyday wear.',
      brand: 'ComfyWear',
      category: 'Hoodies',
      price: 39.99,
      countInStock: 30,
      rating: 4.6,
      numReviews: 18,
    },
    {
      _id: '6',
      name: 'Sports Shorts',
      image: '/images/sports-shorts.jpg',
      description: 'Lightweight and breathable sports shorts.',
      brand: 'Athleisure',
      category: 'Shorts',
      price: 24.99,
      countInStock: 25,
      rating: 4.3,
      numReviews: 22,
    },
    {
      _id: '7',
      name: 'Formal Shirt',
      image: '/images/formal-shirt.jpg',
      description: 'Classic formal shirt with a slim fit.',
      brand: 'OfficeWear',
      category: 'Shirts',
      price: 34.99,
      countInStock: 10,
      rating: 4.4,
      numReviews: 9,
    },
    {
      _id: '8',
      name: 'Summer Dress',
      image: '/images/summer-dress.jpg',
      description: 'Light and airy summer dress for warm days.',
      brand: 'SunnyStyles',
      category: 'Dresses',
      price: 59.99,
      countInStock: 12,
      rating: 4.7,
      numReviews: 14,
    },
    {
      _id: '9',
      name: 'Workout Leggings',
      image: '/images/workout-leggings.jpg',
      description: 'High-performance leggings for your workouts.',
      brand: 'FitGear',
      category: 'Leggings',
      price: 29.99,
      countInStock: 18,
      rating: 4.5,
      numReviews: 20,
    },
    {
      _id: '10',
      name: 'Winter Coat',
      image: '/images/winter-coat.jpg',
      description: 'Warm and stylish coat for the winter season.',
      brand: 'WinterWear',
      category: 'Coats',
      price: 149.99,
      countInStock: 7,
      rating: 4.8,
      numReviews: 11,
    },
  ];
  
  export default products;
  